# Generated by Django 4.2.30 on 2026-05-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_workitemfield_workitemfieldoption_workitemfieldvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='LarkDueReminderLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stage', models.CharField(max_length=16)),
                ('reminder_date', models.DateField()),
                ('sent_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Lark Due Reminder Log',
                'verbose_name_plural': 'Lark Due Reminder Logs',
                'db_table': 'lark_due_reminder_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='larkduereminderlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='larkduereminderlog',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lark_due_reminder_logs', to='db.issue'),
        ),
        migrations.AddField(
            model_name='larkduereminderlog',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lark_due_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='larkduereminderlog',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddConstraint(
            model_name='larkduereminderlog',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'receiver', 'stage', 'reminder_date'), name='uniq_lark_due_reminder_live_issue_receiver_stage_date'),
        ),
        migrations.AlterUniqueTogether(
            name='larkduereminderlog',
            unique_together={('issue', 'receiver', 'stage', 'reminder_date', 'deleted_at')},
        ),
    ]
