# Generated by Django 4.2.30 on 2026-05-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_project_personal'),
    ]

    # NOTE: makemigrations also detected two pre-existing RenameIndex drifts
    # on automationrule/automationrulerun (unrelated to custom fields, a known
    # upstream/automation migration-state drift). Deliberately excluded here —
    # this migration is scoped strictly to the WorkItemField external-id keys.
    operations = [
        migrations.AddField(
            model_name='workitemfield',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workitemfield',
            name='external_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workitemfieldoption',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workitemfieldoption',
            name='external_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
