# Generated by Django 4.2.30 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_workitemfield_external_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiactivitylog',
            name='acting_on_behalf_of',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
